/**
 * 현대IT&E 3차 프로젝트 API 명세서
 * 현대IT&E 3차 프로젝트에 사용되는 API 명세서
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.hoxy.hlivv.data.models


/**
 *
 * @param productId
 * @param productName
 * @param unitPrice
 * @param totalPrice
 * @param discountUnitPrice
 * @param cartQty
 * @param stockQuantity
 * @param arSupported
 * @param qrSupported
 * @param eco
 */
data class CartDto(

    val productId: Long? = null,
    val productName: String? = null,
    val unitPrice: Long? = null,
    val totalPrice: Long? = null,
    val discountUnitPrice: Long? = null,
    val cartQty: Int? = null,
    val stockQuantity: Int? = null,
    val arSupported: Boolean? = null,
    val qrSupported: Boolean? = null,
    val eco: Boolean? = null
)