/**
 * 현대IT&E 3차 프로젝트 API 명세서
 * 현대IT&E 3차 프로젝트에 사용되는 API 명세서
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.hoxy.hlivv.data.models


/**
 *
 * @param codes
 * @param arguments
 * @param defaultMessage
 * @param objectName
 * @param field
 * @param rejectedValue
 * @param bindingFailure
 * @param code
 */
data class FieldError(

    val codes: Array<String>? = null,
    val arguments: Array<Any>? = null,
    val defaultMessage: String? = null,
    val objectName: String? = null,
    val field: String? = null,
    val rejectedValue: Any? = null,
    val bindingFailure: Boolean? = null,
    val code: String? = null
)