/**
 * 현대IT&E 3차 프로젝트 API 명세서
 * 현대IT&E 3차 프로젝트에 사용되는 API 명세서
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.hoxy.hlivv.data.models


/**
 *
 * @param loginId
 * @param name
 * @param phone
 * @param email
 * @param signupDate
 * @param interiorType
 * @param points
 * @param grade
 */
data class MemberResponseDto(

    val loginId: String? = null,
    val name: String? = null,
    val phone: String? = null,
    val email: String? = null,
    val signupDate: java.time.LocalDateTime? = null,
    val interiorType: String? = null,
    val points: Long? = null,
    val grade: Grade? = null
) {
    /**
     *
     * Values: FLOWER,TREE,FOREST
     */
    enum class Grade(val value: String) {
        FLOWER("FLOWER"),
        TREE("TREE"),
        FOREST("FOREST");
    }
}