/**
 * 현대IT&E 3차 프로젝트 API 명세서
 * 현대IT&E 3차 프로젝트에 사용되는 API 명세서
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.hoxy.hlivv.data.models


/**
 *
 * @param year
 * @param month
 * @param day
 * @param orderTotal
 * @param cnt
 */
data class MonthlyOrderSummaryDto(

    val year: Int? = null,
    val month: Int? = null,
    val day: Int? = null,
    val orderTotal: Long? = null,
    val cnt: Long? = null
)