/**
 * 현대IT&E 3차 프로젝트 API 명세서
 * 현대IT&E 3차 프로젝트에 사용되는 API 명세서
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.hoxy.hlivv.data.models

/**
 *
 * @param orderId
 * @param orderRequesterDto
 * @param addressDto
 * @param orderDate
 * @param requestMsg
 * @param subTotal
 * @param orderTotal
 * @param orderCash
 * @param orderPoint
 * @param couponName
 * @param requestDate
 * @param products
 */
data class OrderResDto(

    val orderId: Long? = null,
    val orderRequesterDto: OrderRequesterDto? = null,
    val addressDto: AddressDto? = null,
    val orderDate: java.time.LocalDateTime? = null,
    val requestMsg: String? = null,
    val subTotal: Long? = null,
    val orderTotal: Long? = null,
    val orderCash: Long? = null,
    val orderPoint: Long? = null,
    val couponName: String? = null,
    val requestDate: java.time.LocalDate? = null,
    val products: Array<OrderProductResDto>? = null
)