/**
 * 현대IT&E 3차 프로젝트 API 명세서
 * 현대IT&E 3차 프로젝트에 사용되는 API 명세서
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.hoxy.hlivv.data.models

/**
 *
 * @param totalElements
 * @param totalPages
 * @param size
 * @param content
 * @param number
 * @param sort
 * @param first
 * @param last
 * @param numberOfElements
 * @param pageable
 * @param empty
 */
data class PageCartDto(

    val totalElements: Long? = null,
    val totalPages: Int? = null,
    val size: Int? = null,
    val content: Array<CartDto>? = null,
    val number: Int? = null,
    val sort: SortObject? = null,
    val first: Boolean? = null,
    val last: Boolean? = null,
    val numberOfElements: Int? = null,
    val pageable: PageableObject? = null,
    val empty: Boolean? = null
)