/**
 * 현대IT&E 3차 프로젝트 API 명세서
 * 현대IT&E 3차 프로젝트에 사용되는 API 명세서
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.hoxy.hlivv.data.models

/**
 *
 * @param channel
 * @param escrow
 * @param name
 * @param amount
 * @param currency
 * @param status
 * @param impUid
 * @param cashReceiptIssued
 * @param customerUidUsage
 * @param buyerEmail
 * @param buyerName
 * @param buyerTel
 * @param buyerPostcode
 * @param buyerAddr
 * @param merchantUid
 * @param customData
 * @param customerUid
 * @param cardNumber
 * @param cardQuota
 * @param payMethod
 * @param applyNum
 * @param startedAt
 * @param failedAt
 * @param cancelReason
 * @param embPgProvider
 * @param pgTid
 * @param bankName
 * @param vbankName
 * @param cancelHistory
 * @param receiptUrl
 * @param cardCode
 * @param cancelAmount
 * @param cardType
 * @param vbankDate
 * @param failReason
 * @param paidAt
 * @param vbankHolder
 * @param pgProvider
 * @param vbankIssuedAt
 * @param vbankCode
 * @param vbankNum
 * @param cancelledAt
 * @param cardName
 * @param bankCode
 */
data class Payment(

    val channel: String? = null,
    val escrow: Boolean? = null,
    val name: String? = null,
    val amount: java.math.BigDecimal? = null,
    val currency: String? = null,
    val status: String? = null,
    val impUid: String? = null,
    val cashReceiptIssued: Boolean? = null,
    val customerUidUsage: String? = null,
    val buyerEmail: String? = null,
    val buyerName: String? = null,
    val buyerTel: String? = null,
    val buyerPostcode: String? = null,
    val buyerAddr: String? = null,
    val merchantUid: String? = null,
    val customData: String? = null,
    val customerUid: String? = null,
    val cardNumber: String? = null,
    val cardQuota: Int? = null,
    val payMethod: String? = null,
    val applyNum: String? = null,
    val startedAt: Long? = null,
    val failedAt: java.time.LocalDateTime? = null,
    val cancelReason: String? = null,
    val embPgProvider: String? = null,
    val pgTid: String? = null,
    val bankName: String? = null,
    val vbankName: String? = null,
    val cancelHistory: Array<PaymentCancelDetail>? = null,
    val receiptUrl: String? = null,
    val cardCode: String? = null,
    val cancelAmount: java.math.BigDecimal? = null,
    val cardType: Int? = null,
    val vbankDate: java.time.LocalDateTime? = null,
    val failReason: String? = null,
    val paidAt: java.time.LocalDateTime? = null,
    val vbankHolder: String? = null,
    val pgProvider: String? = null,
    val vbankIssuedAt: Long? = null,
    val vbankCode: String? = null,
    val vbankNum: String? = null,
    val cancelledAt: java.time.LocalDateTime? = null,
    val cardName: String? = null,
    val bankCode: String? = null
)