/**
 * 현대IT&E 3차 프로젝트 API 명세서
 * 현대IT&E 3차 프로젝트에 사용되는 API 명세서
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.hoxy.hlivv.data.models

/**
 *
 * @param id
 * @param name
 * @param productDesc
 * @param productType
 * @param price
 * @param stockQuantity
 * @param discountPercent
 * @param productBrand
 * @param category
 * @param productImages
 * @param productOptions
 * @param restore
 * @param arSupported
 * @param qrSupported
 * @param eco
 */
data class ProductDto(

    val id: Long? = null,
    val name: String? = null,
    val productDesc: String? = null,
    val productType: ProductType? = null,
    val price: Int? = null,
    val stockQuantity: Int? = null,
    val discountPercent: Int? = null,
    val productBrand: String? = null,
    val category: CategoryDto? = null,
    val productImages: Array<ProductImageDto>? = null,
    val productOptions: Array<ProductOptionDto>? = null,
    val restore: Boolean? = null,
    val arSupported: Boolean? = null,
    val qrSupported: Boolean? = null,
    val eco: Boolean? = null
) {
    /**
     *
     * Values: PRODUCT,COLLABO
     */
    enum class ProductType(val value: String) {
        PRODUCT("PRODUCT"),
        COLLABO("COLLABO");
    }
}