/**
 * 현대IT&E 3차 프로젝트 API 명세서
 * 현대IT&E 3차 프로젝트에 사용되는 API 명세서
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.hoxy.hlivv.data.models


/**
 *
 * @param rejectMsg
 * @param productName
 * @param requestGrade
 * @param payback
 * @param inspectedGrade
 * @param subject
 * @param toEmail
 */
data class RestoreEmailDto(

    val rejectMsg: String? = null,
    val productName: String? = null,
    val requestGrade: RequestGrade? = null,
    val payback: Long? = null,
    val inspectedGrade: InspectedGrade? = null,
    val subject: String? = null,
    val toEmail: String? = null
) {
    /**
     *
     * Values: S,A,B,C
     */
    enum class RequestGrade(val value: String) {
        S("S"),
        A("A"),
        B("B"),
        C("C");
    }

    /**
     *
     * Values: S,A,B,C
     */
    enum class InspectedGrade(val value: String) {
        S("S"),
        A("A"),
        B("B"),
        C("C");
    }
}