/**
 * 현대IT&E 3차 프로젝트 API 명세서
 * 현대IT&E 3차 프로젝트에 사용되는 API 명세서
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.hoxy.hlivv.data.models


/**
 *
 * @param restoreStatus
 * @param cnt
 */
data class RestoreStatusDto(

    val restoreStatus: RestoreStatus? = null,
    val cnt: Long? = null
) {
    /**
     *
     * Values: UNDERSCORE,UNDERSCORE_1,UNDERSCORE_2,UNDERSCORE_3,UNDERSCORE_4,UNDERSCORE_5,UNDERSCORE_6,UNDERSCORE_7,UNDERSCORE_8,UNDERSCORE_9
     */
    enum class RestoreStatus(val value: String) {
        UNDERSCORE("접수완료"),
        UNDERSCORE_1("배송받는중"),
        UNDERSCORE_2("검수중"),
        UNDERSCORE_3("검수완료"),
        UNDERSCORE_4("반송중"),
        UNDERSCORE_5("리스토어완료"),
        UNDERSCORE_6("접수취소"),
        UNDERSCORE_7("폐기완료"),
        UNDERSCORE_8("폐기대기"),
        UNDERSCORE_9("반송완료");
    }
}