/**
 * 현대IT&E 3차 프로젝트 API 명세서
 * 현대IT&E 3차 프로젝트에 사용되는 API 명세서
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.hoxy.hlivv.data.models


/**
 *
 * @param productId
 * @param pickUpDate
 * @param requestGrade
 * @param restoreDesc
 * @param whenRejected
 * @param restoreImageUrls
 */
data class RestoreRegisterDto(

    val productId: Long,
    val pickUpDate: java.time.LocalDateTime? = null,
    val requestGrade: RequestGrade,
    val restoreDesc: String? = null,
    val whenRejected: Boolean,
    val restoreImageUrls: Array<String>? = null
) {
    /**
     *
     * Values: S,A,B,C
     */
    enum class RequestGrade(val value: String) {
        S("S"),
        A("A"),
        B("B"),
        C("C");
    }
}