/**
 * 현대IT&E 3차 프로젝트 API 명세서
 * 현대IT&E 3차 프로젝트에 사용되는 API 명세서
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.hoxy.hlivv.data.models

/**
 *
 * @param writer
 * @param reviewDate
 * @param updatedDate
 * @param reviewImages
 * @param reviewText
 * @param star
 */
data class ReviewDto(

    val writer: String? = null,
    val reviewDate: java.time.LocalDateTime? = null,
    val updatedDate: java.time.LocalDateTime? = null,
    val reviewImages: Array<ReviewImageDto>? = null,
    val reviewText: String? = null,
    val star: Int? = null
)