/**
 * 현대IT&E 3차 프로젝트 API 명세서
 * 현대IT&E 3차 프로젝트에 사용되는 API 명세서
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.hoxy.hlivv.data.models


/**
 *
 * @param loginId
 * @param loginPw
 * @param name
 * @param phone
 * @param email
 * @param signupDate
 */
data class SignupDataGenDto(

    val loginId: String,
    val loginPw: String,
    val name: String,
    val phone: String? = null,
    val email: String? = null,
    val signupDate: java.time.LocalDateTime? = null
)